services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "24"
    image: harmonyhub-web:latest
    container_name: harmonyhub
    env_file: .env.example
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: harmonyhub_db
    env_file: .env.example
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Mostly for using Playwright on unsupported Linux distros.
  # https://playwright.dev/docs/docker#remote-connection
  playwright:
    image: mcr.microsoft.com/playwright:v1.59.1
    container_name: harmonyhub_playwright
    ports:
      - 3000:3000
    init: true
    stdin_open: true
    tty: true
    working_dir: /home/pwuser
    user: pwuser
    command: /bin/sh -c "npx -y playwright@1.59.1 run-server --port 3000 --host 0.0.0.0"

volumes:
  db_data:
