import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
              <nav className="navbar">
                  <div className="navbar-name">
                      HarmonyHub
                  </div>
                  <div className="navbar-center">
                    <Link href="/">Home</Link>
                    <Link href="/search">Search</Link>
                    <Link href="/ratings">Ratings</Link>
                    <Link href="/chart">Chart</Link>
                    <Link href="/settings">Settings</Link>
                  </div>
              </nav>
              {children}
      </body>
    </html>
  );
}