import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shadcn-studio/blocks/navbar-component-01/navbar-component-01";
import Footer from "@/components/shadcn-studio/blocks/footer-component-01/footer-component-01";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HarmonyHub",
  description: "Generated by create next app",
};

const navigationData = [
  {
    title: "Chart",
    href: "/chart",
  },
  {
    title: "Ratings",
    href: "/ratings",
  },
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Friends",
    href: "/friends",
  },
  {
    title: "Settings",
    href: "/settings",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
<<<<<<< HEAD
        <nav className="navbar">
          <div className="navbar-name">HarmonyHub</div>
          <div className="navbar-center">
            <Link href="/">Home</Link>
            <Link href="/search">Search</Link>
            <Link href="/ratings">Ratings</Link>
            <Link href="/chart">Chart</Link>
            <Link href="/settings">Settings</Link>
            <Link href="/profile">Profile</Link>
          </div>
        </nav>
        {children}
=======
        <Navbar navigationData={navigationData} />
        <main>{children}</main>
        <Footer />
>>>>>>> origin/UIDesign
      </body>
    </html>
  );
}
